### ISSUE TITLE
Wrong result returned in certain cases

### ISSUE THREAD

**Issue by jverre** [FormidableLabs/delaunay-find#9]
Hi,

I have been having some issues with victory-voronoi-container and have found a potential issue with delaunay-find.

For nearly the same values of `x` and `y`, in one case delaunay.find returns 0 and in another it returns the correct value.
 
I have tried different combinations of x and y and haven't really been able to find a pattern as to why the result it not the same.

Examples:
```
const Delaunay = require("delaunay-find").default;

var scaled_data = [
  [60    ,17113.1],
  [106.5 ,17113.1],
  [153   ,17113.1],
  [199.5 ,17113.1],
  [246   ,17113.1],
  [292.5 ,17113.1],
  [339   ,17113.1],
  [385.5 ,17113.1]]

let delaunay = Delaunay.from(scaled_data)

delaunay.find(300, 17113.1)  // returns 0
```

```
const Delaunay = require("delaunay-find").default;

var scaled_data = [
  [60    ,17113.2],
  [106.5 ,17113.2],
  [153   ,17113.2],
  [199.5 ,17113.2],
  [246   ,17113.2],
  [292.5 ,17113.2],
  [339   ,17113.2],
  [385.5 ,17113.2]]

let delaunay = Delaunay.from(scaled_data)

delaunay.find(300, 17113.2)  // returns 5
```

**Comment by boygirl** [comment]
@jverre Thanks for reporting! This repo is really just a slimmed down clone of `d3-delaunay` with generator functions rewritten to avoid requiring a shim. I will check upstream for updates and similar issues with that project and the underlying `delaunator`

**Comment by nburt** [comment]
I think that I've run into the same problem with Victory Voronoi Container. I created an issue (https://github.com/FormidableLabs/victory/issues/1403) last week in the Victory repo and the code sandbox has some examples of data that causes the issue for us and data that works.

**Comment by boygirl** [comment]
@jverre I've just checked against the latest version of `d3-delaunay` and your first case fails there as well. I will open an issue in that repo.
